import json, collections
# (registro, decisão/motivo) — todos os registros acadêmicos distintos examinados em 22/09/2026
R = [
("Automated room lighting and fan system (RG, 2025)","veículo/texto integral não identificado"),
("Real-time energy monitoring ESP32 (academia.edu, 2026)","veículo/texto integral não identificado"),
("Remote home automation MQTT ESP32 Node-RED (I-SMAC 2024)","sem controle baseado em presença"),
("Dinmohammadi; Farook; Shafiee (Energies, 2025)","INCLUÍDO"),
("Kong et al. (Applied Energy, 2022)","texto integral indisponível"),
("Pang et al. (Energy and Buildings, 2025)","INCLUÍDO"),
("OBC em laboratórios (Energy and Buildings, 2022)","edificação de grande porte"),
("Pang et al. (Energy and Buildings, 2024)","INCLUÍDO"),
("Detecção por imagens térmicas (arXiv, 2025)","não revisado por pares / sem controle"),
("Pinheiro et al. (ASHRAE Trans., 2026)","sem arquitetura computacional (simulação energética)"),
("Pinheiro et al. (JBPS, 2026)","sem arquitetura computacional (simulação energética)"),
("Pang et al. (Applied Energy, 2021)","sem arquitetura computacional (simulação energética)"),
("Termostato inteligente (ASHRAE Journal)","revista técnica, sem arquitetura documentada"),
("OCCUPIED, escritório (2023)","edificação de grande porte"),
("Confiabilidade de sensores residenciais (2022)","sem controle (avaliação de sensor)"),
("Home automation NMap + MQTT (CEE, 2024)","sem controle baseado em presença"),
("Latência ESP32 edge-cloud (Sensors, 2026)","fora do tema (sem controle de iluminação/temperatura)"),
("Aquisição ESP32 nível de água (2024)","fora do tema (sem controle de iluminação/temperatura)"),
("Avaliação ESP-NOW (2026)","fora do tema (sem controle de iluminação/temperatura)"),
("Agentes de borda em IoT (arXiv, 2026)","fora do tema (sem controle de iluminação/temperatura)"),
("Latência MQTT (TCC Theseus, 2026)","tipo de publicação (TCC de graduação)"),
("Segurança MQTT (arXiv)","fora do tema (sem controle de iluminação/temperatura)"),
("Pontes MQTT (arXiv, 2025)","fora do tema (sem controle de iluminação/temperatura)"),
("Automação por voz ESP32 (academia.edu, 2025)","sem controle baseado em presença"),
("Martins — automação MQTT (TCC UFU)","tipo de publicação (TCC de graduação)"),
("Automação com ESP32 (TCC ETEC, 2025)","tipo de publicação (TCC de graduação)"),
("Gomes — automação ESP32 (TCC UFMS, 2023)","tipo de publicação (TCC de graduação)"),
("Iluminação e ar-condicionado IoT (TCC UFPA)","tipo de publicação (TCC de graduação)"),
("LCS com LabVIEW/HDRi (Buildings, 2022)","sem controle baseado em presença"),
("Cheng et al. (Applied Sciences, 2020)","edificação de grande porte"),
("Chew et al. (Energy and Buildings, 2016)","INCLUÍDO"),
("Peruffo et al. (Energy and Buildings, 2015)","anterior a 2016"),
("Brightness adjustment (JLPEA, 2024)","sem controle baseado em presença"),
("LACS em RSSF (Sensors, 2011)","anterior a 2016"),
("Controle distribuído WSAN (Sensors)","anterior a 2016"),
("Iluminação residencial por RSSF (JEDT, 2020)","sem métrica quantitativa no texto acessível"),
("Smart lighting WSAN (2018)","texto integral indisponível"),
("Iluminação distribuída PIDNN (AHSWN, 2013)","anterior a 2016"),
("Mutmainnah; Tristiantoro (Elekterika, 2025)","INCLUÍDO"),
("Iluminação fuzzy ESP32 (IJAIR)","sem controle baseado em presença"),
("Iluminação pública ESP-NOW (JAEST)","ambiente externo"),
("Iluminação pública ESP32 (IJSECS, 2024)","ambiente externo"),
("Dimerização automática (Sci. Reports, 2025)","sem controle baseado em presença"),
("Controlador RNA para escritório (IJEECS, 2018)","sem controle baseado em presença"),
("Smart light controlling system (preprint, 2021)","não revisado por pares / sem controle"),
("Estratégia de iluminação em escritório (Dubai)","edificação de grande porte"),
("Ozcelik (JOAM, 2016)","arquitetura não documentada no texto acessível"),
("LECE (2018)","sem controle baseado em presença"),
]
NAO_ACAD = 16
inc = [r for r,m in R if m=="INCLUÍDO"]
exc = collections.Counter(m for r,m in R if m!="INCLUÍDO")
out = {"identificados": len(R)+NAO_ACAD, "nao_academicos": NAO_ACAD, "triados": len(R),
       "excluidos": sum(exc.values()), "incluidos": len(inc), "motivos": exc.most_common()}
json.dump(out, open('triagem.json','w'), ensure_ascii=False, indent=1); print(json.dumps(out, ensure_ascii=False, indent=1))
